### PR TITLE
keep vcs icon in the "same" position

### PR DESCRIPTION
**Pull request by Raruto**
Minor edit, in order to avoid that the **vcs icon** is added after the **"in local development"** message (_easier to see and understand_)

### CODE REVIEW

**Comment by Raruto** [comment]
oops, what a mess!

_why do we still see all the comments from the previous one?_

**Comment by afragen** [comment]
> oops, what a mess!
> 
> _why do we still see all the comments from the previous one?_

I have no idea.

I'm not certain as to this PR. All it seems to do is move the conditional and filter higher in the `load_hooks()` function. I'm not sure this is what you had in mind. Also a screenshot would be nice.

**Comment by afragen** [comment]
Do you mean like this?

screenshot_22

**Comment by Raruto** [comment]
> All it seems to do is move the conditional and filter higher in the `load_hooks()` function
> ...
> Do you mean like this?

Yep, in this way they still share the same hook priority (15).

**Comment by afragen** [comment]
I've got a fix locally that explicitly ensures the hook priority is correct regardless of when the hook is called.

**Comment by Raruto** [comment]
however in your way https://github.com/afragen/local-development/commit/016e1d15dd9bdd0dd5d21fe57ce00c06a1c0f8f0#diff-e69ddc6ae9435975d1d746184610655e you cannot always be sure that they will always be side by side ( eg. external hook call with priority 17 )

**Comment by afragen** [comment]
True, but we can't count on every possible interaction of other plugins with out code.

**Comment by Raruto** [comment]
yes, but since the execution of the code is sequential, what sense does it make to introduce this "randomness"? (wouldn't the code be even cleaner to read?)

**Comment by afragen** [comment]
I’ll change the priority to be sequential. That should be less _random_. 😉

Are we ready to release?

**Comment by Raruto** [comment]
> Are we ready to release?

👌

**Pull request closed without merging**
