### PR TITLE
Custom Plugin Headers (icon links)

### PR DESCRIPTION
**Pull request by Raruto**
This pull is an early working version based on the following work: [GitHub Link - v1.0.0](https://github.com/szepeviktor/github-link/pull/10).

**TODO:** check if it works on test multisite (I currently don't have one)

### CODE REVIEW

**Comment by afragen** [comment]
What does adding links get us that doesn't already exist from the _View details_ link? If the user can get to the link using the _View details_ link and a properly set up `readme.txt` file, I think we should remove this.

**Comment by afragen** [comment]
I don't like using the `add_plugin_headers` filter any more. I will see about a different solution.

**Comment by afragen** [comment]
We need to make the setting opt in, not opt out. This was a problem when installed on a non-localhost environment for admin bar styling.

**Comment by afragen** [comment]
I was thinking something more along the lines of the following. That way the information is present but not so _in your face_. This doesn't use extra headers and doesn't specify a WP only plugin. Data regarding the branch is present if the user selects _Branch Switching_ from GitHub Updater.

screenshot_20

**Comment by afragen** [comment]
Take a look at the `icons` branch. https://github.com/afragen/local-development/tree/icons

screenshot_21

**Comment by afragen** [comment]
Yes, works in multisite. 😉

**Comment by Raruto** [comment]
> What does adding links get us that doesn't already exist from the View details link?

Maybe nothing, but I remind you that we are not talking about general users.

The main advantage of this modification is that through a glance **it allows us to understand** which and how many plugins are installed via wordpress.org, which are not, and which are present on multiple vcs platforms (**in a standardized way** and without reading too much _boring_ readme files).

> If the user can get to the link using the View details link and a properly set up readme.txt file, I think we should remove this.

Some generally too **strong assumptions**:
- good knowledge of the **WordPress system** by those who use or develop the plugin
- good knowledge of the **English language** by the writer or the reader of the readme file
- rich and **self-explanatory readme files**

> I don't like using the `add_plugin_headers` filter any more. I will see about a different solution.

I inserted it before the autoloader ([source code](https://github.com/afragen/local-development/pull/7/files#diff-eaac4b1c62d2703adc363ef0551fcd0cR53)) because I think **there is something inside the autoloader that breaks** the normal sequence of wordpress calls (if I move it within your current php classes **that filter** does not seem to be executed in time)

> We need to make the setting opt in, not opt out. This was a problem when installed on a non-localhost environment for admin bar styling.

It would be preferable not to let the user take **too many steps after installing the plugin** (think of the immediacy of the [Query Monitor](https://it.wordpress.org/plugins/query-monitor/) plugin, **just install and play!**).

Later I try to think of a solution that does not give problems on real servers.

> I was thinking something more along the lines of the following. That way the information is present but not so in your face. This doesn't use extra headers and doesn't specify a WP only plugin.

I had tried it too (a few years ago), to avoid using the filter, right?

Honestly I prefer the first solution, because:

- the **icons are always in the same place**
- the whole **page appears more orderly**
- the **wordpress icon provides additional information** (although it may seem useless, there are also plugins that are neither on wordpress.org nor on a git host)
- the **`row_meta` can easily get very crowded**

> Yes, works in multisite. 😉

Ok, but maybe not on the multi-themes management page, right?

**Comment by Raruto** [comment]
> Data regarding the branch is present if the user selects Branch Switching from GitHub Updater.

It's true but requires that the developer:
1. know **what** a vcs is
2. know **what** github-updater is
3. **want to use** github-updater to manage its plugins
4. has **downloaded** github-updater
5. has **installed** github-updater
6. has **installed** local-development
7. has **activated** github-updater
8. has **activated** local-development
9. has **visited settings** section of github-updater
10.  has **enabled branch switching** option (in github-updater)
11. has **visited settings** section of local-development
12. has **clicked extras** section of local-development
13. has **enabled vcs icon links** option (in local development)
14. and finally **_has returned to plugin installation page!_**

_that's what I mean these are really too many steps ... ( **just install and play!** )_

**Comment by afragen** [comment]
I will change the icons to enabled by default. I plan on making it work for themes too.

Branch information will **never** work. That data came from GitHub Updater. There is no longer a branch header so it would always display as `master`. Besides, even with GHU the branch information will not display as the branch will be set from whichever branch is active via git locally. GHU specifically doesn't show the branch switcher when the repository is under local development as it would be a way to indirectly modify code you might be working on.

The links come from a `Plugin URI` header in the `readme.txt` file. It's a rather low barrier to entry.

I rather like not having the icon front and center. Adding it after the `In Local Development` line seems more natural and in line with how the plugin displays currently. Having the WP icon is really superfluous and adds additional code that requires expensive calls to dot org. Also, some plugins, Query Monitor, Jetpack, Yoast, add a number of items to the beginning of the plugin and adding more looks excessively crowded to me.

You should take a look at the primary code creating these changes, https://github.com/afragen/local-development/commit/363a4eab71b669039d26603982b1db8ac4ed6f6e
It really is much simpler and works. Additionally, there is no need to use the `extra_plugin_headers` or `extra_theme_headers` filters.

**Comment by afragen** [comment]
Now works with themes and multisite.

**Comment by afragen** [comment]
Keeping the icon in the row meta also makes it more consistent with how in looks for single site themes.

**Comment by Raruto** [comment]
> I will change the icons to enabled by default. I plan on making it work for themes too.
https://github.com/afragen/local-development/pull/7/commits/f2f2de6fe4400c677b5fb41da02ad374c7883acb  should also solve the problem of the always active "green bar" ( localhost visual styling )

> The links come from a `Plugin URI` header in the `readme.txt` file. It's a rather low barrier to entry.

Can you explain better? ( headers in `readme.txt` ?)

> I rather like not having the icon front and center. Adding it after the In Local Development line seems more natural and in line with how the plugin displays currently. Having the WP icon is really superfluous and adds additional code that requires expensive calls to dot org. Also, some plugins, Query Monitor, Jetpack, Yoast, add a number of items to the beginning of the plugin and adding more looks excessively crowded to me.

After all, I agree with the choice.

Maybe the visibility should be improved ( e.g. icon + text, colored label, or some minor change that can attract more attention )

_... let me a while to think better ..._

**Comment by Raruto** [comment]
> I will change the icons to enabled by default. I plan on making it work for themes too.

https://github.com/afragen/local-development/pull/7/commits/f2f2de6fe4400c677b5fb41da02ad374c7883acb should solve the problem of always active green bar ( custom localhost styling )

**Review by afragen — APPROVED** [review]
This looks good.

**Comment by afragen** [comment]
> Can you explain better? ( headers in `readme.txt` ?)

Adding `Plugin URI: https://github.com/afragen/local-development` as a header in `readme.txt` adds the plugin homepage to the _View details_ window.

> Maybe the visibility should be improved ( e.g. icon + text, colored label, or some minor change that can attract more attention )

Let's let this stand as is for a while.

**Comment by afragen** [comment]
Thanks for this PR @Raruto 🥳

**Comment by Raruto** [comment]
> Adding `Plugin URI: https://github.com/afragen/local-development` as a header in `readme.txt` adds the plugin homepage to the View details window.

and of course it's a really poorly documented feature ... [how your readme txt works?](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/)

Is there a real reason for this duplication? ( php + readme file )

> Let's let this stand as is for a while.

Ok, in the next few days I try to think better

**Pull request merged**
